### PR TITLE
Added my pet's entry

### PR DESCRIPTION
**Pull request by Zaris47**
Added my cat's entry in index.html

Please let me know if there are any issues

### CODE REVIEW

**Review by harisdev-netizen — CHANGES_REQUESTED** [review]
The changes made in the PR are good to go. Doesn't seem there is any problem with it so merge it to the main branch.

**Comment by harisdev-netizen** [comment]
> Added my cat's entry in index.html
> 
> Please let me know if there are any issues

@Zaris47 we are now making some changes to allow the users to upload their pet image as well. So do check out the project in a day or two and add your pet image as well.

**Review by harisdev-netizen — APPROVED** [review]

**Comment by Zaris47** [comment]
> The changes made in the PR are good to go. Doesn't seem there is any problem with it so merge it to the main branch.

Thank you. Also this is my first PR and I am not sure how I can merge it, it still says 'Review required' , 'Merge is blocked'



> @Zaris47 we are now making some changes to allow the users to upload their pet image as well. So do check out the project in a day or two and add your pet image as well.

@harisdev-netizen Awesome, looking forwards to it :)

**Comment by harisdev-netizen** [comment]
> > The changes made in the PR are good to go. Doesn't seem there is any problem with it so merge it to the main branch.
> 
> Thank you. Also this is my first PR and I am not sure how I can merge it, it still says 'Review required' , 'Merge is blocked'
> 
> > @Zaris47 we are now making some changes to allow the users to upload their pet image as well. So do check out the project in a day or two and add your pet image as well.
> 
> @harisdev-netizen Awesome, looking forwards to it :)

Do not worry about merging your PR. Owner of this repository will merge your PR to the main branch. I have already approved the changes made.

**Comment by Zaris47** [comment]
> > > The changes made in the PR are good to go. Doesn't seem there is any problem with it so merge it to the main branch.
> > 
> > 
> > Thank you. Also this is my first PR and I am not sure how I can merge it, it still says 'Review required' , 'Merge is blocked'
> > > @Zaris47 we are now making some changes to allow the users to upload their pet image as well. So do check out the project in a day or two and add your pet image as well.
> > 
> > 
> > @harisdev-netizen Awesome, looking forwards to it :)
> 
> Do not worry about merging your PR. Owner of this repository will merge your PR to the main branch. I have already approved the changes made.

Thank you for the clarification 👍

**Comment by gabrysia694** [comment]
Thank you @Zaris47 for contributing and @harisdev-netizen for reviewing! I'm merging the PR right away.

**Review by gabrysia694 — APPROVED** [review]

**Pull request merged**
