### PR TITLE
added MyPetSpotlight

### PR DESCRIPTION
**Pull request by harisdev-netizen**
kindly review the changes

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
Looks good but please move it above the comment on 166 line :)

**Comment by harisdev-netizen** [comment]
> Looks good but please move it above the comment on 166 line :)

Okay, I will make changes as you've mentioned.

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
I meant above like over the comment on 166 line so that every added div by contributors are between `<!-- Add your pet below -->` and `<!-- Add your pet above -->` comments  :)

**Comment by harisdev-netizen** [comment]
> I meant above like over the comment on 166 line so that every added div by contributors are between `<!-- Add your pet below -->` and `<!-- Add your pet above -->` comments :)

You want me to add comment after MyPetSpotlight info right?

**Comment by harisdev-netizen** [comment]
> I meant above like over the comment on 166 line so that every added div by contributors are between `<!-- Add your pet below -->` and `<!-- Add your pet above -->` comments :)

Review my PR now. I hope I did it right this time.

**Review by gabrysia694 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
