### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by its-your-invi**

### CODE REVIEW

**Comment by its-your-invi** [comment]
https://github.com/gabrysia694/MyPetSpotlight/issues/33

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
obraz_2023-04-20_221524577
I got two small suggestions. Border radius is different in cards and pictures which creates space between corners, I know it used to be like that originally but I think it's time to change it. Could you set border-radius to be equal both in pictures and cards? Could be 15px in top right and left img so it matches .card. Contributors have added 2 or 3 personality traits while the size of the cards is the same for all animal profiles. Because of that pictures are sometimes misaligned, like in Luna's card there's additional free space at the top. Maybe we could set card height to auto? Apart from that, it looks so pretty! ❤️

**Comment by its-your-invi** [comment]
> obraz_2023-04-20_221524577 I got two small suggestions. Border radius is different in cards and pictures which creates space between corners, I know it used to be like that originally but I think it's time to change it. Could you set border-radius to be equal both in pictures and cards? Could be 15px in top right and left img so it matches .card. Contributors have added 2 or 3 personality traits while the size of the cards is the same for all animal profiles. Because of that pictures are sometimes misaligned, like in Luna's card there's additional free space at the top. Maybe we could set card height to auto? Apart from that, it looks so pretty! ❤️

Actually, I didn't set the height to auto because I thought cards with the same height would look beautiful. Though I changed the height to auto as the misaligned pictures destroy the beauty of the cards

**Review by lewisushindi — APPROVED** [review]

**Comment by its-your-invi** [comment]
I think owner name of the pet should be added with the card

**Review by gabrysia694 — APPROVED** [review]

**Comment by gabrysia694** [comment]
> I think owner name of the pet should be added with the card

good idea, would you like to work on that?

**Comment by its-your-invi** [comment]
> > I think owner name of the pet should be added with the card
> 
> good idea, would you like to work on that?

Yeah sure ... But for that I need the owner name of all pets.

**Comment by gabrysia694** [comment]
> > > I think owner name of the pet should be added with the card
> > 
> > 
> > good idea, would you like to work on that?
> 
> Yeah sure ... But for that I need the owner name of all pets.

that could be tricky. you'd have to look at closed PR of people who added their pets and then check the names on their github profiles. I can do that and give you the list unless you're willing to do that yourself

**Comment by its-your-invi** [comment]
> that could be tricky. you'd have to look at closed PR of people who added their pets and then check the names on their github profiles. I can do that and give you the list unless you're willing to do that yourself

Yeah I have already listed the owner names searching the old PRs. But I'm unable to find the owner of these 4 pets: Luna, Gruba, Bubble, Shadow

**Comment by its-your-invi** [comment]
My Code is ready. If you kindly give the owner names of those pets with their github username, I'll make a PR

**Comment by gabrysia694** [comment]
> My Code is ready. If you kindly give the owner names of those pets with their github username, I'll make a PR

Luna and Gruba were added by me, Bubble was added by Vishal @Vishal-Parasram and Shadow by Haris @harisdev-netizen :)

**Comment by its-your-invi** [comment]
> Luna and Gruba were added by me, Bubble was added by Vishal @Vishal-Parasram and Shadow by Haris @harisdev-netizen :)
Thanks for the information :D 

Check the PR

**Comment by harisdev-netizen** [comment]
> > My Code is ready. If you kindly give the owner names of those pets with their github username, I'll make a PR
> 
> Luna and Gruba were added by me, Bubble was added by Vishal @Vishal-Parasram and Shadow by Haris @harisdev-netizen :)

This Open-Source keeps getting better and better. Amazing. 😍

**Comment by harisdev-netizen** [comment]
@gabrysia694 if you check the last four pets their heights are not exactly the same. There is a bit difference in the pixels.

**Comment by its-your-invi** [comment]
> @gabrysia694 if you check the last four pets their heights are not exactly the same. There is a bit difference in the pixels.


The heights of the cards are not the same since their height is set to 'auto'. If we fix the height of the card, it will introduce other bugs. You can read the previous discussion of this thread

**Comment by its-your-invi** [comment]
> It's because we didn't specify the exact number of personality traits that could be listed. How about we put a scrollbar on personality div if it has more than 3 elements? And then set all card's height to the same value.

I added two properties to the .content ul { height: 90px; overflow-y: scroll; } for the above changes.
But this happen which isn't looking good.
1. For three or two elements:
image

2. For more than three elements
image

**Comment by its-your-invi** [comment]
I think we should create a new issue and allow others to share their opinions on this matter.

**Comment by harisdev-netizen** [comment]
> > It's because we didn't specify the exact number of personality traits that could be listed. How about we put a scrollbar on personality div if it has more than 3 elements? And then set all card's height to the same value.
> 
> For these, I added two properties to the .content ul { height: 90px; overflow-y: scroll; } But this happen which isn't looking good.
> 
> 1. For three or two elements:
>    image
> 2. For more than three elements
>    image

I will check the code, and I will check why this happens.

**Comment by its-your-invi** [comment]
> I will check the code, and I will check why this happens.

This is occuring for the scrollbar. I changed the default scrollbar for better looking. And that properties of main scrollbar is occuring here. Check the first lines of style.css

**Comment by gabrysia694** [comment]
obraz_2023-05-04_013538878

```
 const personalityDivs = document.querySelectorAll('.personality');

  personalityDivs.forEach(personalityDiv => {
    const liElements = personalityDiv.querySelectorAll('li');
    const liCount = liElements.length;
    const ulElements = personalityDiv.querySelectorAll('ul');

    if (liCount > 3) {
      ulElements.forEach(ulElement => {
        ulElement.style.cssText = "height: 90px; overflow-y: scroll; padding-right: 10px;";
      });
    }
  });
```
wrote some js code to add scroll only to cards that have more than 3 personality traits, what do you think?

**Comment by harisdev-netizen** [comment]
> obraz_2023-05-04_013538878
> 
> ```
>  const personalityDivs = document.querySelectorAll('.personality');
> 
>   personalityDivs.forEach(personalityDiv => {
>     const liElements = personalityDiv.querySelectorAll('li');
>     const liCount = liElements.length;
>     const ulElements = personalityDiv.querySelectorAll('ul');
> 
>     if (liCount > 3) {
>       ulElements.forEach(ulElement => {
>         ulElement.style.cssText = "height: 90px; overflow-y: scroll; padding-right: 10px;";
>       });
>     }
>   });
> ```
> 
> wrote some js code to add scroll only to cards that have more than 3 personality traits, what do you think?

The code seems reasonable and should achieve the desired functionality of only adding scroll to cards that have more than 3 personality traits. Perfect 🚀

**Comment by gabrysia694** [comment]
Awesome, I'm glad you both approve! Would any of you like to add this js code, set card's height and test the code overall?

**Comment by its-your-invi** [comment]
> Awesome, I'm glad you both approve! Would any of you like to add this js code, set card's height and test the code overall?

I just made some changes: Scrollbar of Personality div, fixed the list style 

image

I think now it's looking perfect.

**Comment by gabrysia694** [comment]
> > Awesome, I'm glad you both approve! Would any of you like to add this js code, set card's height and test the code overall?
> 
> I just made some changes: Scrollbar of Personality div, fixed the list style
> 
> image
> 
> I think now it's looking perfect.

it does look perfect, I'll be happy to merge it once you create a PR

**Comment by harisdev-netizen** [comment]
> Awesome, I'm glad you both approve! Would any of you like to add this js code, set card's height and test the code overall?

Sorry @gabrysia694 I had been pretty busy these few weeks 😐

**Pull request merged**
