### PR TITLE
Add pictures to the cards #22

### PR DESCRIPTION
**Pull request by Yashdon999**
Add pictures to the cards #22 
As you say changing  the  Alt=" "  name is done

### CODE REVIEW

**Comment by Yashdon999** [comment]
Can you open Readme File Updating issue and assign me 
i want to Update

**Review by gabrysia694 — APPROVED** [review]
Thank you for contributing!

**Comment by gabrysia694** [comment]
> Can you open Readme File Updating issue and assign me i want to Update

Sure but what would you like to update?

**Comment by Yashdon999** [comment]
your readme looks very simple 
That's why i want to update 
@gabrysia694

**Comment by gabrysia694** [comment]
> your readme looks very simple That's why i want to update @gabrysia694

Okay, please open a new issue and I'll assign you to it right away

**Pull request merged**
