### PR TITLE
Added image & Changes to CSS

### PR DESCRIPTION
**Pull request by harisdev-netizen**
Added images to the cards and made changes to CSS for making **class = "border"** to center of the **class="card"** container. Review the PR and merge it to the main.

### CODE REVIEW

**Review by harisdev-netizen — COMMENTED** [review]
Review the PR

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
The whole card of cat August is doubled. The very last row of cards could also have a bit of space so it doesn't stick to the bottom of the screen. Other than that, looks perfect!

**Review by harisdev-netizen — COMMENTED** [review]
PR

**Comment by harisdev-netizen** [comment]
> 

Done.

**Review by gabrysia694 — APPROVED** [review]

**Pull request merged**
