### PR TITLE
Enhancements: Info file and HTML improvements

### PR DESCRIPTION
**Pull request by helloakash1701**
Dear Repository Maintainers,

I hope this message finds you well. I am excited to contribute to the MyPetSpotlight_info repository and help improve and expand our pet lovers community. After carefully reviewing the project and understanding its objectives, I have made some valuable additions that I believe will enhance the overall experience for community members.

Firstly, I have created an informative file, "info.txt," which provides an overview of our community's purpose, goals, and key initiatives. This file aims to give newcomers a clear understanding of what our community stands for and how they can actively participate and contribute.

Additionally, I have made some edits to the HTML files, adding details of my pet. These changes aim to make it easier for community members to access relevant information, engage in discussions, and contribute to the growth of our community.

I have thoroughly tested these modifications on my local environment to ensure their correctness and compatibility. However, I eagerly await your feedback and suggestions. I believe in the collaborative nature of open source projects and look forward to refining my contributions based on your valuable insights.

To review and merge these changes, I have created a pull request titled "Enhancements: Info file and HTML improvements."  I have provided a detailed description of the changes, highlighting the specific files and lines of code that were modified. Please feel free to examine the pull request and share your thoughts.

I genuinely appreciate the time and effort you put into maintaining this repository and fostering a thriving pet lovers community. It would be an honor for me to contribute to this cause and collaborate with fellow pet enthusiasts.

Thank you for considering my contributions. I eagerly await your feedback and the opportunity to work with you to improve and expand our pet lovers community.

Best regards,
Akash Mishra

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
Hello @helloakash1701, we already have a similar file called `README.md`, so please move some information from `info.txt` there and delete `info.txt` so we can have all of it in one place. The rest of your code looks nice and I'll gladly merge it once you make the changes :)

**Comment by helloakash1701** [comment]
> Hello @helloakash1701, we already have a similar file called `README.md`, so please move some information from `info.txt` there and delete `info.txt` so we can have all of it in one place. The rest of your code looks nice and I'll gladly merge it once you make the changes :)

Thankyou for the update. I have deleted the info.txt kindly look into it.

**Review by gabrysia694 — APPROVED** [review]
looks good now, thank you!

**Comment by gabrysia694** [comment]
@helloakash1701 i've got another open-source project called Gym-Junkies if you'd like to contribute to one more :)

**Comment by helloakash1701** [comment]
> @helloakash1701 i've got another open-source project called Gym-Junkies if you'd like to contribute to one more :)

Sure would love to.

**Pull request merged**
