### PR TITLE
Bugs are fixed

### LINKED ISSUE #50: [BUG] misaligned cards on Safari browser
342809351_578447887449610_6039262296569712189_n

Seems like the content of 3 cards moved to the very top of a page when displayed on Safari browser. I don't know what it looks like on desktop though.

### PR DESCRIPTION
**Pull request by its-your-invi**
Closed #50 

Now the cards are in their own position in Safari Browser : 
image

I just added the style 'flex: 1' to the content div to fill up the remaining space. As a result, some lines in JS code is no longer needed.

### CODE REVIEW

**Comment by its-your-invi** [comment]
Besides I have tested this site in all browsers. Everything is fine.

**Review by gabrysia694 — APPROVED** [review]

**Comment by gabrysia694** [comment]
> Besides I have tested this site in all browsers. Everything is fine.

Perfect, thank you so much @its-your-invi ❤️

**Comment by gabrysia694** [comment]
> @gabrysia694 I have an exciting suggestion for you! You should create a Discord Community where we can discuss bugs, find resolutions, add exciting new features, and make enhancements together.
> 
> Since this project is beginner-friendly, it will attract more beginners to create PRs and provide a fantastic learning opportunity for everyone involved :D

That's a great idea! I was also thinking about moving our website to React since `index.html` is getting long and once we create a Discord Community which will attract even more people, it might get hard to maintain. What do you think? :)

**Comment by its-your-invi** [comment]
>
> That's a great idea! I was also thinking about moving our website to React since `index.html` is getting long and once we create a Discord Community which will attract even more people, it might get hard to maintain. What do you think? :)

I believe we should reconsider moving this to React. By keeping it as it is, we enable everyone to contribute, just like in the recent case where someone with basic knowledge of HTML, CSS, and JS could make a PR. 

By the way, if you're up for it, I can take on the role of the maintainer. LOL :)

**Comment by gabrysia694** [comment]
> > That's a great idea! I was also thinking about moving our website to React since `index.html` is getting long and once we create a Discord Community which will attract even more people, it might get hard to maintain. What do you think? :)
> 
> I believe we should reconsider moving this to React. By keeping it as it is, we enable everyone to contribute, just like in the recent case where someone with basic knowledge of HTML, CSS, and JS could make a PR.
> 
> By the way, if you're up for it, I can take on the role of the maintainer. LOL :)

you think so? hmm maybe you're right. let's hold off on moving it to React then. we can always get back to the idea once `index.html` gets unmanageable.

that's a good idea! you've put tons of work into this project and you know it well enough to become a maintainer so i'll gladly give you the rights ❤️

**Comment by its-your-invi** [comment]
> 
> you think so? hmm maybe you're right. let's hold off on moving it to React then. we can always get back to the idea once `index.html` gets unmanageable.
> 
> that's a good idea! you've put tons of work into this project and you know it well enough to become a maintainer so i'll gladly give you the rights ❤️

Thanks for the invitation :) 🎉

**Comment by its-your-invi** [comment]
> 
> That's a great idea! I was also thinking about moving our website to React since `index.html` is getting long and once we create a Discord Community which will attract even more people, it might get hard to maintain. What do you think? :)

What are your thoughts on creating a Discord community? ʘ⁠‿⁠ʘ

**Comment by gabrysia694** [comment]
> > That's a great idea! I was also thinking about moving our website to React since `index.html` is getting long and once we create a Discord Community which will attract even more people, it might get hard to maintain. What do you think? :)
> 
> What are your thoughts on creating a Discord community? ʘ⁠‿⁠ʘ

we can create it! would you like to take care of that?

**Comment by its-your-invi** [comment]
> > 
> > What are your thoughts on creating a Discord community? ʘ⁠‿⁠ʘ
> 
> we can create it! would you like to take care of that?

Sure why not :⁠-⁠)

**Comment by its-your-invi** [comment]
> you think so? hmm maybe you're right. let's hold off on moving it to React then. we can always get back to the idea once `index.html` gets unmanageable.
> 
> that's a good idea! you've put tons of work into this project and you know it well enough to become a maintainer so i'll gladly give you the rights ❤️

I have a humble idea to minimize the index.html code. One approach we can explore is utilizing a template engine to dynamically generate HTML code based on the data.

 I noticed that previous attempts by others to reduce the size of the index.html file may not be actively pursued or might have encountered challenges. With your permission, may I give it a try to implement this idea ?

**Comment by gabrysia694** [comment]
> > you think so? hmm maybe you're right. let's hold off on moving it to React then. we can always get back to the idea once `index.html` gets unmanageable.
> > that's a good idea! you've put tons of work into this project and you know it well enough to become a maintainer so i'll gladly give you the rights ❤️
> 
> I have a humble idea to minimize the index.html code. One approach we can explore is utilizing a template engine to dynamically generate HTML code based on the data.
> 
> I noticed that previous attempts by others to reduce the size of the index.html file may not be actively pursued or might have encountered challenges. With your permission, may I give it a try to implement this idea ?

of course @its-your-invi! I'll be happy to take a look at what you'll create

**Pull request merged**
