### PR TITLE
AddingMyPet

### PR DESCRIPTION
**Pull request by harisdev-netizen**
Added feature to upload pet photos issue10

### CODE REVIEW

**Comment by harisdev-netizen** [comment]
But now the problem is that each individual users will have to make a PR and upload their cat image. I mean would they? Or should I upload some default images for future contributors?

**Comment by gabrysia694** [comment]
I think you need to add the feature to the updated version of index.html, which includes all the animal cards that have been added ever since you added yours or the merge won't go through. The feature itself looks great! I suggest centering the `<div class="border">` within the `<div class="card">` to improve the overall appearance of the card, especially with the image at the top. What do you think?

I think we could add some random pictures of animals to the cards that are already on the page and I'll ping contributors to make a PR and change the picture to the one of their animal if they wish to. We also have to update CONTRIBUTING.md to let people know about the new change.

**Comment by harisdev-netizen** [comment]
> I think you need to add the feature to the updated version of index.html, which includes all the animal cards that have been added ever since you added yours or the merge won't go through. The feature itself looks great! I suggest centering the `<div class="border">` within the `<div class="card">` to improve the overall appearance of the card, especially with the image at the top. What do you think?
> 
> I think we could add some random pictures of animals to the cards that are already on the page and I'll ping contributors to make a PR and change the picture to the one of their animal if they wish to. We also have to update CONTRIBUTING.md to let people know about the new change.

Yeah I giving a though of that as well that for now we will add images for the pets by our own so that the new users willing to contribute gets the idea. And yeah I gave it a thought of centering the **card** but we didn't talked about that so I didn't do it without your consent. I'll do as you have mentioned. And do not worry about making changes to **CONTRIBUTE.md** I'll do that as well after I am done with this task.

**Comment by harisdev-netizen** [comment]
> > I think you need to add the feature to the updated version of index.html, which includes all the animal cards that have been added ever since you added yours or the merge won't go through. The feature itself looks great! I suggest centering the `<div class="border">` within the `<div class="card">` to improve the overall appearance of the card, especially with the image at the top. What do you think?
> > I think we could add some random pictures of animals to the cards that are already on the page and I'll ping contributors to make a PR and change the picture to the one of their animal if they wish to. We also have to update CONTRIBUTING.md to let people know about the new change.
> 
> Yeah I gave it a though of that as well that for now we will add images for the pets by our own so that the new users willing to contribute gets the idea. And yeah I gave it a thought of centering the **card** but we didn't talked about that so I didn't do it without your consent. I'll do as you have mentioned. And do not worry about making changes to **CONTRIBUTE.md** I'll do that as well after I am done with this task.

Centering the **.border** div would be great. I have also created a new issue. Do check that as well.

**Comment by gabrysia694** [comment]
> > I think you need to add the feature to the updated version of index.html, which includes all the animal cards that have been added ever since you added yours or the merge won't go through. The feature itself looks great! I suggest centering the `<div class="border">` within the `<div class="card">` to improve the overall appearance of the card, especially with the image at the top. What do you think?
> > I think we could add some random pictures of animals to the cards that are already on the page and I'll ping contributors to make a PR and change the picture to the one of their animal if they wish to. We also have to update CONTRIBUTING.md to let people know about the new change.
> 
> Yeah I gave it a though of that as well that for now we will add images for the pets by our own so that the new users willing to contribute gets the idea. And yeah I gave it a thought of centering the **card** but we didn't talked about that so I didn't do it without your consent. I'll do as you have mentioned. And do not worry about making changes to **CONTRIBUTE.md** I'll do that as well after I am done with this task.

Perfect, thank you so much! Take your time. If you need any help, let me know!

**Comment by harisdev-netizen** [comment]
> > > I think you need to add the feature to the updated version of index.html, which includes all the animal cards that have been added ever since you added yours or the merge won't go through. The feature itself looks great! I suggest centering the `<div class="border">` within the `<div class="card">` to improve the overall appearance of the card, especially with the image at the top. What do you think?
> > > I think we could add some random pictures of animals to the cards that are already on the page and I'll ping contributors to make a PR and change the picture to the one of their animal if they wish to. We also have to update CONTRIBUTING.md to let people know about the new change.
> > 
> > 
> > Yeah I gave it a though of that as well that for now we will add images for the pets by our own so that the new users willing to contribute gets the idea. And yeah I gave it a thought of centering the **card** but we didn't talked about that so I didn't do it without your consent. I'll do as you have mentioned. And do not worry about making changes to **CONTRIBUTE.md** I'll do that as well after I am done with this task.
> 
> Perfect, thank you so much! Take your time. If you need any help, let me know!

I have **fetched** the **main branch** and **merge** it with **addingMyPet** my branch but I do not see the updated **index.html** in **addingMyPet**

**Pull request closed without merging**
